# Generated by Django 4.2 on 2024-08-20 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0010_alter_savingaccount_id_alter_savingdeposit_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingaccount',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='commod',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='divine_touch',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='interest',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='loan_repay',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=8),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='rss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='saving_type',
            field=models.CharField(choices=[('Oracle', 'Oracle'), ('Teller', 'Teller')], default='Oracle', max_length=6),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='savings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='sp_sav',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024),
        ),
        migrations.AlterField(
            model_name='savingaccount',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saving_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
