# Generated by Django 4.0.4 on 2024-08-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0011_remove_savingaccount_current_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingaccount',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='loan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='loan_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='normal_savings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
