# Generated by Django 4.0.4 on 2024-08-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0012_savingaccount_balance_savingaccount_loan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingaccount',
            old_name='saving_type',
            new_name='payment_type',
        ),
        migrations.RemoveField(
            model_name='savingaccount',
            name='savings',
        ),
    ]
