# Generated by Django 4.0.4 on 2024-08-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0013_rename_saving_type_savingaccount_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingaccount',
            name='received_two',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
