# Generated by Django 4.0.4 on 2024-08-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0014_savingaccount_received_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingaccount',
            name='received_two',
        ),
    ]
