# Generated by Django 4.0.4 on 2024-08-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0015_remove_savingaccount_received_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingaccount',
            name='received',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
