# Generated by Django 4.0.4 on 2024-09-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0019_alter_savingaccount_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingaccount',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=9),
        ),
    ]
