# Generated by Django 4.0.4 on 2024-09-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0021_rename_commod_savingaccount_commod_repay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingaccount',
            name='commod',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='interest',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='loan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
