# Generated by Django 5.1.2 on 2024-11-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0023_savingaccount_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingaccount',
            old_name='balance',
            new_name='savings',
        ),
        migrations.RemoveField(
            model_name='savingaccount',
            name='normal_savings',
        ),
        migrations.RemoveField(
            model_name='savingaccount',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='savingaccount',
            name='sp_sav',
        ),
        migrations.AlterField(
            model_name='savingaccount',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=11),
        ),
    ]
