# Generated by Django 5.1.2 on 2024-11-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0024_rename_balance_savingaccount_savings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingaccount',
            name='commodity_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='divine_touch_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='interest_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='loan_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='rss_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='savings_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='share_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
