# Generated by Django 5.1.2 on 2025-08-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0028_remove_savingaccount_commod_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingaccount",
            name="month",
            field=models.IntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=8,
            ),
        ),
        migrations.AlterField(
            model_name="savingaccount",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2000, 2000),
                    (2001, 2001),
                    (2002, 2002),
                    (2003, 2003),
                    (2004, 2004),
                    (2005, 2005),
                    (2006, 2006),
                    (2007, 2007),
                    (2008, 2008),
                    (2009, 2009),
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                    (2023, 2023),
                    (2024, 2024),
                    (2025, 2025),
                ],
                default=2025,
            ),
        ),
    ]
