# Generated by Django 4.2 on 2024-08-27 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0012_alter_loanaccount_id_alter_loanissue_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanaccount',
            old_name='total_principal',
            new_name='loan',
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='debit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='loan_type',
            field=models.CharField(choices=[('Loan', 'Loan'), ('Interest', 'Interest'), ('Commodity', 'Commodity')], default='Loan', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
