# Generated by Django 4.2 on 2024-08-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_id_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='member_images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
