# Generated by Django 4.2 on 2024-08-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_member_groups_member_is_active_member_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mem_number',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
