# Generated by Django 4.2 on 2024-08-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_member_mem_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='other_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
