# Generated by Django 4.2.11 on 2024-09-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.CharField(max_length=11),
        ),
    ]
